config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  root 'groups#index'

  resources :groups, except: [:destroy] do
    member do
      get 'candidates'
    end
    resources :members, only: [:create, :destroy]
    resources :join_requests, only: [:index, :create]
    resources :songs do
      collection do
        get 'authors'
      end
    end
    resources :tags, except: [:new, :show]
    resources :presentations
  end

  resources :songs, only: [] do
    resources :comments, only: [:create]
  end

  resources :presentations, only: [] do
    resources :comments, only: [:create]
    member do
      get 'play'
    end
  end

  resources :comments, only: [:update, :destroy]

  resources :join_requests, only: [] do
    member do
      put :accept
      put :reject
    end
  end

  resources :colors, only: [:index]
end

app/models/presentation.rb
# == Schema Information
#
# Table name: presentations
#
#  id         :integer          not null, primary key
#  local      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  group_id   :integer          not null
#  date_time  :datetime
#
# Indexes
#
#  index_presentations_on_group_id  (group_id)
#
# Foreign Keys
#
#  fk_rails_...  (group_id => groups.id)
#

class Presentation < ApplicationRecord
  belongs_to :group
  has_many :presentation_songs, -> { order(:index) }, inverse_of: :presentation, dependent: :destroy
  has_many :songs, through: :presentation_songs
  has_many :comments, as: :target
  validates :local, :date_time, :group, :presentation_songs, presence: true

  def add_song(song)
    index = presentation_songs.size + 1
    presentation_songs.build(song: song, index: index)
  end
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  include PresentationsHelper

  before_action :set_presentation, only: [:show, :edit, :update, :play]
  before_action :set_group, except: [:play]
  before_action do
    require_group_member(@group || @presentation.group)
  end

  def index
    @year  = params[:year] || DateTime.now.year
    @month = params[:month] || DateTime.now.month

    if (1..12).to_a.include?(@month.to_i)
      @presentations = @group.presentations.where('extract(month from date_time) = ?', @month).where('extract(year from date_time) = ?', @year).order(:date_time)
    else
      @presentations = @group.presentations.where('extract(year from date_time) = ?', @year).order(:date_time)
    end
  end

  def show; end

  def new
    @presentation = @group.presentations.build
  end

  def edit
    @date = presentation_date(@presentation)
    @time = presentation_time(@presentation)
  end

  def create
    @presentation = @group.presentations.build(presentation_params)
    @presentation.date_time = create_date_time
    add_songs
    @presentation.validate

    if @presentation.save
      redirect_to group_presentations_path(@group)
    else
      render :new
    end
  end

  def update
    @presentation.date_time = create_date_time
    @presentation.presentation_songs.destroy_all
    add_songs

    if @presentation.update(presentation_params)
      redirect_to group_presentations_path(@group)
    else
      render :edit, status: :bad_request
    end
  end

  def destroy
    Presentation.destroy(params[:id])
    redirect_to group_presentations_path(@group)
  end

  def play
    render :play, layout: 'blank'
  end

  private
  def set_presentation
    @presentation = Presentation.find(params[:id])
  end

  def presentation_params
    params.require(:presentation).permit(:local)
  end

  def add_songs
    if params[:song_ids].present?
      songs = params[:song_ids].split(",").map { |id| @group.songs.find(id) }
      songs.each { |song| @presentation.add_song(song) }
    end
  end

  def create_date_time
    @date = params[:date]
    @time = params[:time]

    if @date.present? && @time.present?
      DateTime.parse("#{@date} #{@time}")
    else
      flash.now[:date] = I18n.t('activerecord.custom_errors.presentation.date') unless @date.present?
      flash.now[:time] = I18n.t('activerecord.custom_errors.presentation.time') unless @time.present?
      return nil
    end
  end
end

app/helpers/presentations_helper.rb
module PresentationsHelper
  def song_ids(presentation)
    song_ids = presentation.presentation_songs.map { |presentation_song| presentation_song.song.id }
    song_ids.join(",")
  end

  def months
    months = I18n.t('date.month_names').to_a.compact
    months.unshift(I18n.t('date.all_months'))
    months.each_with_index.map{ |month, index| [month, index] }
  end

  def years
    Presentation.all.map { |p| p.date_time.year }.uniq
  end

  def past_presentation_time(presentation)
    return if presentation.nil?
    prefix = t('date.time_ago_prefix')
    time_past = time_ago_in_words(presentation.date_time)
    "#{prefix} #{time_past}"
  end

  def time_until_presentation(presentation)
    return if presentation.nil?
    prefix = t('date.from_now_prefix')
    time_until = time_ago_in_words(presentation.date_time)
    "#{prefix} #{time_until}"
  end

  def presentation_date_with_day_of_week(presentation)
    "#{l(presentation.date_time, format: '%A')}, #{presentation.date_time&.strftime('%d/%m/%Y')}"
  end

  def presentation_date(presentation)
    presentation.date_time&.strftime('%d/%m/%Y')
  end

  def presentation_time(presentation)
    presentation.date_time&.strftime('%H:%M')
  end
end

app/views/presentations/_deletion_modal.html.erb
<div id="deletion_confirmation_modal" class="modal">
  <div class="modal-content">
    <h4><%= t('caution') %></h4>
    <p><%= t('presentations.delete.message') %></p>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action modal-close waves-effect btn-flat"><%= t('actions.cancel') %></a>
    <%= link_to t('actions.delete'), group_presentation_path(current_group, @presentation), method: :delete, class: "modal-action modal-close waves-effect btn-flat red-text text-darken-3" %>
  </div>
</div>

app/views/presentations/_form.html.erb
<% content_for :stylesheet do %>
  <%= stylesheet_link_tag 'pages/presentations/form' %>
<% end %>
<div class="row">
  <div class="col s12 m8 offset-m2">
    <%= form_with(model: [ current_group, @presentation ]) do |f| %>
      <div class="input-field">
        <%= f.label :date %>
        <%= text_field_tag :date, @date, { class: 'datepicker' } %>
        <% if flash[:date] %>
          <span class="error"><%= flash[:date] %></span>
        <% end %>
      </div>

      <div class="input-field">
        <%= f.label :time %>
        <%= text_field_tag :time, @time, { class: 'timepicker' } %>
        <% if flash[:time] %>
          <span class="error"><%= flash[:time] %></span>
        <% end %>
      </div>

      <div class="input-field">
        <%= f.label :local %>
        <%= f.text_field :local %>
      </div>

      <div>
        <songs-selector
          id="songs_selector"
          :songs="<%= render 'components/songs/songs_list.json.jbuilder', songs: current_group.songs %>"
          :presentation-songs="<%= render 'components/songs/songs_list.json.jbuilder', songs: @presentation.songs %>">
        </songs-selector>

        <% if @presentation.errors[:presentation_songs].present? %>
          <span class="error"><%= @presentation.errors[:presentation_songs].first %></span>
        <% end %>
      </div>

      <div class="actions right-align">
        <% if @presentation.persisted? %>
          <button class="btn-danger" @click="showModal('#deletion_confirmation_modal')" type="button">
            <%= t('actions.delete') %>
          </button>
        <% end %>
        <%= button_tag t('actions.create'), { class: 'btn', type: 'submit' } %>
      </div>
    <% end %>
  </div>
</div>

<% if @presentation.persisted? %>
  <%= render 'deletion_modal' %>
<% end %>

app/views/presentations/_search_form.html.erb
<div class='presentations-search-form'>
  <%= form_tag(group_presentations_path(current_group), method: 'get') do %>
    <div class="col s12 m4 input-field no-margin-top">
      <%= select_tag 'month', options_for_select(months, @month) %>
    </div>
    <% if years.count > 1 %>
      <div class="col s12 m4 input-field no-margin-top">
        <%= select_tag 'year', options_for_select(years, @year) %>
      </div>
    <% end %>
    <div class="col s12 m4 right-align-on-small">
      <%= button_tag class: 'btn-floating' do %>
        <i class="material-icons">search</i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/presentations/edit.html.erb
<%= render "form" %>

app/views/presentations/index.html.erb
<% content_for :stylesheet do %>
  <%= stylesheet_link_tag 'pages/presentations/index' %>
<% end %>

<section-heading><%= I18n.t('presentations.index') %></section-heading>

<div class="row actions-menu">
  <%= render "search_form" %>
  <% if @presentations.any? %>
    <%= link_to new_group_presentation_path(current_group), class: 'btn-floating add-button' do %>
      <i class="material-icons">add</i>
    <% end %>
  <% end %>
</div>

<div class="row">
  <% @presentations.each do |presentation| %>
      <div class="col s12 m4">
        <%= link_to group_presentation_path(current_group, presentation) do %>
          <presentation-card :presentation="<%= render "components/presentation_card.json.jbuilder", presentation: presentation %>" ></presentation-card>
        <% end %>
      </div>
  <% end %>

  <% if @presentations.empty? %>
    <div class="center-align">
      <p><%= "#{ t('presentations.no_presentations_in') } #{ t('date.month_names')[@month.to_i] }" %></p>

      <%= link_to new_group_presentation_path(current_group), class: 'btn-floating add-button' do %>
        <i class="material-icons">add</i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/presentations/new.html.erb
<%= render "form" %>

app/views/presentations/play.html.erb
<% content_for :stylesheet do %>
  <%= stylesheet_link_tag 'pages/presentations/play' %>
<% end %>

<div class="menu right-align">
  <button type="button" class="btn-flat-bordered hide-on-large-only horizontal-margin" data-enable-nosleep>
    <i class="material-icons left">lightbulb_outline</i>
    <%= t('presentations.enableWakeLock') %>
  </button>

  <%= link_to group_presentation_path(current_group, @presentation), { class: 'btn-floating', 'data-disable-nosleep' => nil } do %>
    <i class="material-icons">close</i>
  <% end %>
</div>

<div id="play_view" class="row">
  <% @presentation.presentation_songs.each do |ps| %>
    <presentation-song-card :presentation-song="<%= render 'components/presentation_song_card.json.jbuilder', presentation_song: ps %>"></presentation-song-card>
  <% end %>
</div>

app/views/presentations/show.html.erb
<% content_for :stylesheet do %>
  <%= stylesheet_link_tag 'pages/presentations/show' %>
<% end %>

<div class="right-align">
  <%= link_to edit_group_presentation_path(current_group, @presentation), class: 'btn-floating horizontal-margin' do %>
    <i class="material-icons">edit</i>
  <% end %>
  <%= link_to play_presentation_path(@presentation), class: 'btn-floating' do %>
    <i class="material-icons">play_arrow</i>
  <% end %>
</div>

<div id="presentation_info" class="center-align">
  <div class="info">
    <i class="fa fa-calendar"></i><h5><%= presentation_date(@presentation) %></h5>
  </div>
  <div class="vertical-separator hide-on-small-only"></div>
  <div class="info">
    <i class="fa fa-clock-o"></i><h5><%= presentation_time(@presentation) %></h5>
  </div>
  <div class="vertical-separator hide-on-small-only"></div>
  <div class="info">
    <i class="fa fa-map-marker"></i><h5><%= @presentation.local %></h5>
  </div>
</div>

<div class="collection">
  <% @presentation.presentation_songs.each do |ps| %>
    <%= link_to group_song_path(current_group, ps.song), class: "collection-item" do %>
      <div>
        <span class="song-index"><%= ps.index %></span>
        <%= ps.song.title %>
        <span class="light-text"><small><%= "- #{ ps.song.author }" if ps.song.author.present? %></small></span>
      </div>
    <% end %>
  <% end %>
</div>

<div id="comments">
  <% @presentation.comments.each do |comment| %>
    <comment
      :comment="<%= render 'components/comment.json.jbuilder', comment: comment %>"
      :can-edit="<%= current_user.id.equal?(comment.commenter.id) %>">
    </comment>
  <% end %>
</div>

<%= render "comments/form", { target: @presentation, comment: @presentation.comments.build } %>