config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  root 'groups#index'

  resources :groups, except: [:destroy] do
    member do
      get 'candidates'
    end
    resources :members, only: [:create, :destroy]
    resources :join_requests, only: [:index, :create]
    resources :songs do
      collection do
        get 'authors'
      end
    end
    resources :tags, except: [:new, :show]
    resources :presentations
  end

  resources :songs, only: [] do
    resources :comments, only: [:create]
  end

  resources :presentations, only: [] do
    resources :comments, only: [:create]
    member do
      get 'play'
    end
  end

  resources :comments, only: [:update, :destroy]

  resources :join_requests, only: [] do
    member do
      put :accept
      put :reject
    end
  end

  resources :colors, only: [:index]
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  title      :string
#  author     :string
#  tone       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  group_id   :integer          not null
#
# Indexes
#
#  index_songs_on_group_id  (group_id)
#
# Foreign Keys
#
#  fk_rails_...  (group_id => groups.id)
#

class Song < ApplicationRecord
  belongs_to :group
  has_and_belongs_to_many :tags
  has_many :presentation_songs
  has_many :presentations, through: :presentation_songs
  has_many :comments, -> { order(:created_at) }, as: :target, dependent: :destroy
  validates :title, :group, presence: true
  validates :tone, format: { with: /\A[A-G](b|#)?m?\z/ }

  def last_presentation
    presentations.where('DATE(date_time) < ?', DateTime.now).order(date_time: :desc).first
  end

  def next_presentation
    presentations.where('DATE(date_time) > ?', DateTime.now).order(:date_time).first
  end

  def times_played
    presentations.where('DATE(date_time) < ?', DateTime.now).order(date_time: :desc).size
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :set_group
  before_action do
    require_group_member(@group)
  end

  def index
    @songs = @group.songs.order(:title)
  end

  def show
    @last_presentation = @song.last_presentation
    @next_presentation = @song.next_presentation
  end

  def new
    @song = Song.new
  end

  def edit; end

  def create
    @song = @group.songs.build(song_params)
    if @song.save
      redirect_to group_songs_path(@group)
    else
      render :new, status: :bad_request
    end
  end

  def update
    if @song.update(song_params)
      redirect_to group_songs_path(@group)
    else
      render :edit, status: :bad_request
    end
  end

  def destroy
    Song.destroy(params[:id])
    redirect_to group_songs_path(@group)
  end

  def authors
    @authors = @group.songs.map(&:author).uniq.sort
    render json: @authors
  end

  private
  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title, :author, :tone, tag_ids: [])
  end
end

app/helpers/songs_helper.rb
module SongsHelper
  def get_tags_from_songs(songs)
    tags = songs.map(&:tags)
    tags.flatten.uniq
  end

  def can_delete_song?(song)
    song.persisted? && song.presentations.empty?
  end
end

app/views/songs/_deletion_modal.html.erb
<div id="deletion_confirmation_modal" class="modal">
  <div class="modal-content">
    <h4><%= t('caution') %></h4>
    <p><%= t('songs.delete.message') %></p>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action modal-close waves-effect btn-flat"><%= t('actions.cancel') %></a>
    <%= link_to t('actions.delete'), group_song_path(current_group, @song), method: :delete, class: "modal-action modal-close waves-effect btn-flat red-text text-darken-3" %>
  </div>
</div>

app/views/songs/_form.html.erb
<div class="row">
  <div class="col s12 m6 offset-m3">

    <%= form_for [@group, @song] do |f| %>
    <div class="input-field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="input-field">
      <%= f.label :author %>
      <%= f.text_field :author, { "data-group_id": @group.id, autocomplete: "off", class: "autocomplete" } %>
    </div>

    <div class="input-field">
      <%= f.label :tone %>
      <%= f.text_field :tone %>
    </div>

    <div class="input-field">
      <%= f.label :tags %>
      <%= f.collection_select(:tag_ids, @group.tags, :id, :name, {}, { multiple: true }) %>
    </div>

    <div class="actions right-align">
      <% if can_delete_song?(@song) %>
        <button class="btn-danger" @click="showModal('#deletion_confirmation_modal')" type="button">
          <%= t('actions.delete') %>
        </button>
      <% end %>
      <%= button_tag t('actions.create'), { type: 'submit', class: 'btn' } %>
    </div>
    <% end %>

  </div>
</div>

<% if @song.persisted? %>
  <%= render "deletion_modal" %>
<% end %>

app/views/songs/_index.html.erb
<% content_for :stylesheet do %>
  <%= stylesheet_link_tag 'pages/songs/index' %>
<% end %>

<ul class="collection">
  <% songs.each do |song| %>
    <%= link_to edit_group_song_path(@group, song), class: "collection-item" do %>
      <div>
        <%= song.title %>
        <span class="grey-text text-lighten-1 secondary-content"><%= song.tone %></span>
        <div class="tags-container secondary-content">
          <% song.tags.each do |tag| %>
            <tag class="song-tag" :tag="<%= render template: 'songs/tag.json.jbuilder', locals: { tag: tag } %>"></tag>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</ul>

app/views/songs/_search_form.html.erb
<div class="songs-search-form">
  <%= form_tag group_songs_path(@group), remote: true, method: :get, id: 'songs_list_form' do |f| %>
    <%= hidden_field_tag 'tags_ids', @tags_ids, id: 'tags_ids' %>
    <%= hidden_field_tag 'page', @page, id: 'page' %>
    <%= hidden_field_tag 'items_per_page', @items_per_page, id: 'items_per_page' %>

    <tags-filter
      :tags="<%= render 'components/tags_filter.json.jbuilder', tags: @group.tags %>"
      :current-group-id="<%= current_group.id %>">
    </tags-filter>

    <div id="search_input_container" class="input-field">
      <%= text_field_tag 'query', nil, placeholder: t('songs.search_by') %>
    </div>

    <div class="right-align">
      <%= button_tag type: 'submit', class: 'btn-floating vertical-margin' do %>
        <i class="material-icons">search</i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/songs/edit.html.erb
<%= render "form" %>

app/views/songs/index.html.erb
<% if @songs.any? %>
  <section-heading><%= I18n.t('songs.index') %></section-heading>
  <div class="right-align">
    <%= link_to new_group_song_path(current_group), class: 'btn-floating' do %>
      <i class="material-icons">add</i>
    <% end %>
  </div>

  <songs-list :songs="<%= render 'components/songs/songs_list.json.jbuilder', songs: @songs %>"></songs-list>
<% else %>
  <div class="center-align">
    <p><%= t('no_songs') %></p>

    <%= link_to new_group_song_path(current_group), class: 'btn-floating' do %>
      <i class="material-icons">add</i>
    <% end %>
  </div>
<% end %>

app/views/songs/new.html.erb
<%= render "form" %>

app/views/songs/show.html.erb
<% content_for :stylesheet do %>
  <%= stylesheet_link_tag 'pages/songs/show' %>
<% end %>

<div class="right-align">
  <%= link_to edit_group_song_path(current_group, @song), class: 'btn-floating' do %>
    <i class="material-icons">edit</i>
  <% end %>
</div>

<div class="title">
  <%= @song.title %>
</div>

<p class="author"><%= @song.author %></p>

<div class="presentations">
  <% if @last_presentation %>
    <%= link_to group_presentation_path(current_group, @last_presentation) do %>
      <song-presentation
        title="<%= t('songs.show.last_presentation') %>"
        date="<%= presentation_date_with_day_of_week(@last_presentation) %>"
        time_distance="<%= past_presentation_time(@last_presentation) %>">
      </song-presentation>
    <% end %>
  <% end %>

  <% if @next_presentation %>
    <%= link_to group_presentation_path(current_group, @next_presentation) do %>
      <song-presentation
        title="<%= t('songs.show.next_presentation') %>"
        date="<%= presentation_date_with_day_of_week(@next_presentation) %>"
        time_distance="<%= time_until_presentation(@next_presentation) %>">
      </song-presentation>
    <% end %>
  <% end %>
</div>

<%= render "comments/comments", { target: @song } %>