config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  root 'groups#index'

  resources :groups, except: [:destroy] do
    member do
      get 'candidates'
    end
    resources :members, only: [:create, :destroy]
    resources :join_requests, only: [:index, :create]
    resources :songs do
      collection do
        get 'authors'
      end
    end
    resources :tags, except: [:new, :show]
    resources :presentations
  end

  resources :songs, only: [] do
    resources :comments, only: [:create]
  end

  resources :presentations, only: [] do
    resources :comments, only: [:create]
    member do
      get 'play'
    end
  end

  resources :comments, only: [:update, :destroy]

  resources :join_requests, only: [] do
    member do
      put :accept
      put :reject
    end
  end

  resources :colors, only: [:index]
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  color_id   :integer          not null
#  group_id   :bigint(8)
#
# Indexes
#
#  index_tags_on_color_id  (color_id)
#  index_tags_on_group_id  (group_id)
#
# Foreign Keys
#
#  fk_rails_...  (group_id => groups.id)
#

class Tag < ApplicationRecord
  belongs_to :color
  belongs_to :group
  has_and_belongs_to_many :songs
  validates :name, presence: true
  validates :name, uniqueness: { scope: :group }
  validates :color, uniqueness: { scope: :group }
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_group
  before_action do
    require_group_member(@group)
  end

  def index
    @tag = Tag.new
    @tags = @group.tags

    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
    @tag = @group.tags.find(params[:id])
  end

  def create
    @tag = @group.tags.build(tag_params)
    if @tag.save
      redirect_to group_tags_path(@group)
    else
      @tags = @group.tags
      render :index
    end
  end

  def update
    @tag = @group.tags.find(params[:id])
    if @tag.update(tag_params)
      redirect_to group_tags_path(@group)
    else
      render :edit
    end
  end

  def destroy
    @group.tags.delete(params[:id])
    redirect_to group_tags_path(@group)
  end

  private
  def tag_params
    params.require(:tag).permit(:name, :color_id)
  end
end

app/views/tags/_deletion_modal.html.erb
<div id="deletion_confirmation_modal" class="modal">
  <div class="modal-content">
    <h4><%= t('caution') %></h4>
    <p><%= t('tags.delete.message', count: tag.songs.count) %></p>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action modal-close waves-effect btn-flat"><%= t('actions.cancel') %></a>
    <%= link_to t('actions.delete'), group_tag_path(current_group, tag), method: :delete, class: "modal-action modal-close waves-effect btn-flat red-text text-darken-3" %>
  </div>
</div>

app/views/tags/_form.html.erb
<%= form_with(model: [ current_group, tag ]) do |f| %>
  <div class="input-field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div class="color-picker">
    <%= f.hidden_field :color_id, { id: 'tag_color_id' } %>
    <tag-color-picker default-color="<%= tag.color&.id %>"></tag-color-picker>
    <span class="error"><%= tag.errors[:color].first %></span>
  </div>

  <div class="actions right-align">
    <% if tag.persisted? %>
      <button class="btn-danger modal-trigger" @click="showModal('#deletion_confirmation_modal')" type="button">
        <%= t('actions.delete') %>
      </button>
    <% end %>
    <%= button_tag t('actions.create'), { type: 'submit', class: 'btn' } %>
  </div>

  <% if tag.persisted? %>
    <%= render "deletion_modal", tag: tag %>
  <% end %>

<% end %>

app/views/tags/edit.html.erb
<%= render "form", tag: @tag %>

app/views/tags/index.html.erb
<% content_for :stylesheet do %>
  <%= stylesheet_link_tag 'pages/tags/index' %>
<% end %>

<section id="tag_form">
  <%= render "form", tag: @tag %>
</section>

<ul class="collection">
  <% @tags.each do |tag| %>
    <%= link_to edit_group_tag_path(current_group, tag), class: "collection-item" do %>
      <i class="material-icons tiny" style="color: <%= tag.color.code %>;">local_offer</i>
      <%= tag.name %>
    <% end %>
  <% end %>
</ul>