config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  root 'groups#index'

  resources :groups, except: [:destroy] do
    member do
      get 'candidates'
    end
    resources :members, only: [:create, :destroy]
    resources :join_requests, only: [:index, :create]
    resources :songs do
      collection do
        get 'authors'
      end
    end
    resources :tags, except: [:new, :show]
    resources :presentations
  end

  resources :songs, only: [] do
    resources :comments, only: [:create]
  end

  resources :presentations, only: [] do
    resources :comments, only: [:create]
    member do
      get 'play'
    end
  end

  resources :comments, only: [:update, :destroy]

  resources :join_requests, only: [] do
    member do
      put :accept
      put :reject
    end
  end

  resources :colors, only: [:index]
end

app/views/layouts/_browser_menu.html.erb
<div id="browser-menu" class="hide-on-med-and-down">
  <ul>
    <li>
      <!-- logo -->
      <%= link_to (image_tag("logo.svg")), root_path, class: "browser-logo hide-on-med-and-down" %>
    </li>

    <% if current_group %>
      <!-- Group name -->
      <li class="group-name"><b><%= current_group.name %></b></li>

      <!-- Join requests -->
      <% if current_group.join_requests_to_be_accepted.any? %>
        <%= link_to group_join_requests_path(current_group), class: 'btn-floating pulse' do %>
          <li>
            <i class="material-icons">person_add</i>
          </li>
        <% end %>
      <% end %>

      <!-- Presentations -->
      <li><%= link_to t('presentations.index'), group_presentations_path(current_group) %></li>

      <!-- Song -->
      <li><%= link_to t('songs.index'), group_songs_path(current_user.last_group) %></li>

      <!-- Membros -->
      <li><%= link_to t('groups.members'), group_path(current_group) %></li>

      <li>
        <div class="vertical-separator"></div>
      </li>
    <% end %>

    <!-- Groups -->
    <li><%= link_to t('groups.index'), groups_path %></li>
  </ul>

  <ul class="right">
    <li>
      <!-- Account menu button -->
      <a class="dropdown-trigger menu-item" href="#!" data-target="account_menu">
        <%= image_tag current_user.avatar.url, class: 'circle nav-avatar' %>
        <i class="material-icons right">arrow_drop_down</i>
      </a>
    </li>
  </ul>
</div>

<!-- Account menu -->
<ul id="account_menu" class="dropdown-content">

  <!-- My account -->
  <li><%= link_to t('registrations.edit'), edit_user_registration_path(current_user) %> </li>

  <li class="divider"></li>

  <!-- Logout -->
  <li><%= link_to t('sessions.destroy'), destroy_user_session_path, method: :delete %></li>

</ul>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <header>
    <nav>
      <div class="nav-wrapper">
        <!-- Group name -->
        <% if current_group %>
          <span class="group-name hide-on-large-only"><strong><%= current_group.name %></strong></span>
        <% end %>

        <!-- Mobile menu -->
        <%= render 'layouts/mobile_menu' %>

        <!-- Menu -->
        <%= render 'layouts/browser_menu' %>
      </div>
    </nav>
  </header>
<% end %>

app/views/layouts/_mobile_menu.html.erb
<!-- Mobile menu button -->
<a href="#" data-target="mobile-menu" class="sidenav-trigger"><i class="material-icons">menu</i></a>

<!-- Mobile menu -->
<div class="sidenav" id="mobile-menu">
  <div class="header">
    <%= link_to edit_user_registration_path(current_user), class: 'center-align' do %>
      <i><%= image_tag current_user.avatar.url, class: 'circle responsive-img nav-avatar' %></i>
      <%= current_user.full_name %>
    <% end %>

    <div class="divider"></div>

    <% if current_group %>
      <h6><%= current_group.name %></h6>
    <% end %>
  </div>

  <ul>
    <% unless current_group.nil? %>
      <!-- Presentations -->
      <li> <%= link_to t('presentations.index'), group_presentations_path(current_group) %> </li>

      <!-- Songs -->
      <li> <%= link_to t('songs.index'), group_songs_path(current_user.last_group) %> </li>

      <!-- Membros -->
      <li><%= link_to t('groups.members'), group_path(current_group) %></li>
    <% end %>

    <!-- Groups -->
    <li> <%= link_to t('groups.index'), groups_path %> </li>

    <!-- Exit -->
    <li> <%= link_to t('sessions.destroy'), destroy_user_session_path, method: :delete %> </li>
  </ul>

  <!-- logo -->
  <%= link_to (image_tag("logo.svg")), root_path, class: "mobile-logo" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>What We Play</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= yield :stylesheet %>
    <%= favicon_link_tag %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <main
      id="app"
      class="container"
      :data-locale="'<%= I18n.locale %>'"
      :data-group-id="'<%= current_group&.id %>'">
      <%= yield %>
    </main>

    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>What We Play</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= yield :stylesheet %>
    <%= favicon_link_tag %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <main id="app" class="container">
      <%= yield %>
    </main>

    <%= javascript_pack_tag 'application' %>

  </body>
</html>